# Generated by Django 5.2.10 on 2026-01-18 09:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'Сообщения',
                'default_related_name': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'точка',
                'verbose_name_plural': 'Точки',
            },
        ),
    ]
