# Generated by Django 5.2.10 on 2026-01-18 16:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomessages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Точка'),
        ),
    ]
