# Generated by Django 5.2.10 on 2026-01-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomessages', '0003_alter_point_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='geomessages.point', verbose_name='Точка'),
        ),
    ]
