# Generated by Django 5.2.10 on 2026-01-18 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomessages', '0004_alter_message_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='message',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomessages.point', verbose_name='Точка'),
        ),
    ]
